import type { Metadata } from "next";
import { Inter, Inconsolate } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";

const Inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

const Inconsolate = Inconsolate({
  variable: "--font-inconsolate",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${inconsolate.variable} antialiased`}
        suppressHydrationWarning
      >
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
